version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gestao-estoque
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: gestao-estoque
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migrations
    depends_on:
      - db
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/gestao-estoque
      FLYWAY_USER: myuser
      FLYWAY_PASSWORD: mypassword
    volumes:
      - ./migrations:/flyway/sql
    command: -connectRetries=10 migrate

volumes:
  postgres_data:
