name: Run Flyway Migrations

on:
  push:
    paths:
      - 'database/migrations/**'
    branches:
      - main

  workflow_dispatch: # permite executar manualmente

jobs:
  migrate:
    name: Flyway Migration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/database/migrations:/flyway/sql \
            flyway/flyway:latest \
            -url=jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }} \
            -user=${{ secrets.DB_USER }} \
            -password=${{ secrets.DB_PASSWORD }} \
            -connectRetries=10 \
            migrate
